### PR TITLE
fix: making structured outputs work with tools

### LINKED ISSUE #326: bug: GSXChatCompletion fails when structured output and tools are used together
Fails without error. In addition to a fix we should add a test case to verify.

### PR DESCRIPTION
**Pull request by dereklegenzoff**
Fixes #326

Specifically:
- Adds support for structured outputs to work with tools
- Adds a test for structured output with test
- Removes a couple of unnecessary params from toolExcecutor
- Fixes a couple of places where `ToolExecutor` was still showing in the trace.
- fixes some typos in examples
- Adds a structured output example with tool calls
- remove's `toolExecutorImpl`'s dependency on context since all it was doing was checking for context again

### CODE REVIEW

File: packages/gensx-openai/src/structured-output.tsx [hunk 1]
```diff
@@ -49,29 +49,37 @@ export const structuredOutputImpl = async <T,>(
...
       const toolCalls = completion.choices[0].message.tool_calls;
       // If we have tool calls, execute them and make another completion
-      if (toolCalls?.length && tools) {
-        const toolResult = await gsx.execute<ChatCompletionOutput>(
-          <ToolExecutor
-            tools={tools}
-            toolCalls={toolCalls}
-            messages={[...messages, completion.choices[0].message]}
-            model={rest.model}
+      while (toolCalls?.length && tools) {
```
Comment (jmoseley) [inline packages/gensx-openai/src/structured-output.tsx:63]: Is this supposed to be a while loop? I don't see where `toolCalls` is modified.

Comment (dereklegenzoff) [reply packages/gensx-openai/src/structured-output.tsx:63]: yeah, it needs to be a while loop in case the model does multiple rounds of tool calls...but you make a good point. This will always only ever run once because there's a return statement in the loop.

Comment (dereklegenzoff) [reply packages/gensx-openai/src/structured-output.tsx]: okay fixed and confirmed it works by temproarily disabling parallel tool calls: https://app.gensx.com/gensx/executions/01JMX7GP1J46Z8EZE2BSBZ69Q0?workflowName=ToolsWithStructuredOutputWorkflow

**Review by jmoseley — APPROVED** [review]
